version: "3.8"

services:
    app:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            FLASK_ENV: development
        depends_on:
            - psql
    psql:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 2021
            